#!/bin/bash
#
# Perform necessary chef-provisioner setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Thank you for installing chef-provisioner!"

ln -sf /opt/chef-provisioner/bin/chef-provisioner-ctl /usr/bin || error_exit "Cannot link chef-provisioner-ctl in /usr/bin"

exit 0
